### Parsing

In [1]:
from TwitterAPI_parser_luhang import *
import os

/Users/zeningduan/anaconda3/envs/VecOpt-env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [15]:
#Enter the directory path of your JSON files here:
input_dir = '/Users/zeningduan/Desktop/Collaboration projects/Ukraine Russia project/Script/JSON files folder'

#Enter the directory path of your csv output file here:
output_dir = '/Users/zeningduan/Desktop/Collaboration projects/Ukraine Russia project/Script/csv files folder/'

#Enter your csv output file name here:
output_name = 'Merged file.csv'

### Mode selection
- Mode 1: Combine and parse all JSON files into a single CSV output file
- Mode 2: Parse JSON files individually and generate separate CSV output files

In [40]:
all_files = glob.glob(os.path.join(input_dir, "*.json"))

for file in all_files: #Load each of the JSON files from the input folder
    filename = os.path.basename(file)
    
    with open(file) as f:
    
        json_data = twarc.expansions.flatten(json.loads(f.read()))
        df = pd.json_normalize(json_data)
        df = extract_referenced_tweets(df)
        df = add_full_text(df)
        df = extract_expanded_urls(df)
        df = extract_media_urls(df)
        print("The length of the CSV file", filename, "after parsing: " + str(len(df)))
        #Write the merged CSV file after parsing to the output folder
    df.to_csv(output_dir + filename)

The length of the CSV file 2022101_3.json after parsing: 467
The length of the CSV file 2022101_2.json after parsing: 463
The length of the CSV file 2022101_4.json after parsing: 471
The length of the CSV file 2022101_1.json after parsing: 475
The length of the CSV file 2022101_0.json after parsing: 469

In [30]:


filepath = '/Users/zeningduan/Desktop/Collaboration projects/Ukraine Russia project/Script/JSON files folder/2022101_3.json'

filename = os.path.basename(filepath)
print(filename)
type(filename)

2022101_3.json

str

In [16]:
all_files = glob.glob(os.path.join(input_dir, "*.json"))
parsed_df = []
for file in all_files: #Load each of the JSON files from the input folder
    #print(file)
    with open(file) as f:
        json_data = twarc.expansions.flatten(json.loads(f.read()))
        df = pd.json_normalize(json_data)
        df = extract_referenced_tweets(df)
        df = add_full_text(df)
        df = extract_expanded_urls(df)
        df = extract_media_urls(df)
        parsed_df.append(df)

parsed_data = pd.concat(parsed_df, ignore_index=True) #concat all the JSON files in the list into one dataframe
print("Total length of the merged CSV file after parsing: " + str(len(parsed_data)))
#Write the merged CSV file after parsing to the output folder
parsed_data.to_csv(output_dir + output_name)

Total length of the merged CSV file after parsing: 2345

## Check the parsed CSV file

In [17]:
import pandas as pd

In [20]:
path = '/Users/zeningduan/Desktop/Collaboration projects/Ukraine Russia project/Script/csv files folder/'

In [21]:
data = pd.read_csv(path + 'Merged file.csv')

In [6]:
data

,Unnamed: 0,reply_settings,author_id,created_at,conversation_id,id,possibly_sensitive,edit_history_tweet_ids,lang,referenced_tweets,...,attachments.media.type,attachments.media.url,attachments.media.url_total_number,textual_url_number,author.entities.description.cashtags,in_reply_to_user.withheld.country_codes,attachments.poll_ids,attachments.poll.id,attachments.poll.options,entities.cashtags
0,0,everyone,1498449982965223430,2022-10-01T23:58:10.000Z,1576360858380210177,1576360858380210177,False,['1576360858380210177'],en,"[{'type': 'retweeted', 'id': '1576346581426917...",...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,everyone,1469972461395476483,2022-10-01T23:58:10.000Z,1576360857776590848,1576360857776590848,False,['1576360857776590848'],en,"[{'type': 'retweeted', 'id': '1576057281837666...",...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,everyone,2434162616,2022-10-01T23:58:10.000Z,1576360857734246400,1576360857734246400,False,['1576360857734246400'],en,"[{'type': 'retweeted', 'id': '1576218383476920...",...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,everyone,1524428662107521026,2022-10-01T23:58:10.000Z,1576360857348755456,1576360857348755456,False,['1576360857348755456'],en,"[{'type': 'retweeted', 'id': '1576134238310924...",...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,everyone,1451205768745668609,2022-10-01T23:58:10.000Z,1576360856266608640,1576360856266608640,False,['1576360856266608640'],en,"[{'type': 'retweeted', 'id': '1576360840378298...",...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2340,2340,everyone,106810372,2022-10-01T23:59:24.000Z,1576361169157169157,1576361169157169157,False,['1576361169157169157'],en,"[{'type': 'retweeted', 'id': '1575853684852150...",...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2341,2341,everyone,2828468524,2022-10-01T23:59:24.000Z,1576324821558099968,1576361168616456195,False,['1576361168616456195'],en,"[{'type': 'replied_to', 'id': '157636054024680...",...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2342,2342,everyone,1281659299597619201,2022-10-01T23:59:24.000Z,1576361168536735744,1576361168536735744,False,['1576361168536735744'],en,"[{'type': 'retweeted', 'id': '1576343176520290...",...,photo,https://pbs.twimg.com/media/FeBLwufXoAApvOA.jpg,1,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2343,2343,everyone,1247606632009195520,2022-10-01T23:59:24.000Z,1576361168418967552,1576361168418967552,False,['1576361168418967552'],en,"[{'type': 'retweeted', 'id': '1576360989700009...",...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2344,2344,everyone,1560729272771383297,2022-10-01T23:59:24.000Z,1576361168318660608,1576361168318660608,False,['1576361168318660608'],en,"[{'type': 'retweeted', 'id': '1576313811598200...",...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
data.columns

Index(['Unnamed: 0', 'reply_settings', 'author_id', 'created_at',
       'conversation_id', 'id', 'possibly_sensitive', 'edit_history_tweet_ids',
       'lang', 'referenced_tweets', 'text', 'public_metrics.retweet_count',
       'public_metrics.reply_count', 'public_metrics.like_count',
       'public_metrics.quote_count', 'public_metrics.impression_count',
       'entities.mentions', 'entities.annotations', 'author.created_at',
       'author.profile_image_url', 'author.location',
       'author.entities.description.hashtags', 'author.protected',
       'author.public_metrics.followers_count',
       'author.public_metrics.following_count',
       'author.public_metrics.tweet_count',
       'author.public_metrics.listed_count', 'author.description',
       'author.verified', 'author.name', 'author.pinned_tweet_id',
       'author.username', 'author.id', 'entities.hashtags', 'entities.urls',
       'attachments.media_keys', 'attachments.media',
       'author.entities.url.urls', 'author.url', 'in_reply_to_user_id',
       'in_reply_to_user.created_at', 'in_reply_to_user.profile_image_url',
       'in_reply_to_user.location', 'in_reply_to_user.protected',
       'in_reply_to_user.public_metrics.followers_count',
       'in_reply_to_user.public_metrics.following_count',
       'in_reply_to_user.public_metrics.tweet_count',
       'in_reply_to_user.public_metrics.listed_count',
       'in_reply_to_user.description', 'in_reply_to_user.verified',
       'in_reply_to_user.name', 'in_reply_to_user.pinned_tweet_id',
       'in_reply_to_user.username', 'in_reply_to_user.id',
       'in_reply_to_user.entities.url.urls', 'in_reply_to_user.url',
       'in_reply_to_user.entities.description.mentions',
       'author.entities.description.urls',
       'in_reply_to_user.entities.description.hashtags',
       'author.entities.description.mentions',
       'in_reply_to_user.entities.description.urls', 'withheld.copyright',
       'withheld.country_codes', 'geo.place_id', 'geo.place_type',
       'geo.country_code', 'geo.name', 'geo.id', 'geo.geo.type',
       'geo.geo.bbox', 'geo.full_name', 'geo.country',
       'referenced_tweets.text', 'referenced_tweets.type',
       'referenced_tweets.id', 'referenced_tweets.author_id',
       'referenced_tweets.possibly_sensitive',
       'referenced_tweets.conversation_id', 'referenced_tweets.lang',
       'referenced_tweets.source', 'referenced_tweets.reply_settings',
       'referenced_tweets.entities', 'referenced_tweets.public_metrics',
       'referenced_tweets.attachments', 'referenced_tweets.author',
       'text_full', 'entities.urls.expanded_url',
       'entities.urls.expanded_url_total_number', 'attachments.media.type',
       'attachments.media.url', 'attachments.media.url_total_number',
       'textual_url_number', 'author.entities.description.cashtags',
       'in_reply_to_user.withheld.country_codes', 'attachments.poll_ids',
       'attachments.poll.id', 'attachments.poll.options', 'entities.cashtags'],
      dtype='object')

In [22]:
set(data['referenced_tweets.type'])

{'original', 'quoted', 'quoted replied_to', 'replied_to', 'retweeted'}

In [9]:
data['conversation_id']

0       1576360858380210177
1       1576360857776590848
2       1576360857734246400
3       1576360857348755456
4       1576360856266608640
               ...
2340    1576361169157169157
2341    1576324821558099968
2342    1576361168536735744
2343    1576361168418967552
2344    1576361168318660608
Name: conversation_id, Length: 2345, dtype: int64

In [ ]:
#https://developer.twitter.com/en/docs/twitter-api/expansions